name: PR Verify

on:
  pull_request:
    branches: [ master ]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Find and Replace
#        uses: jacobtomlinson/gha-find-replace@master
#        with:
#          find: "TOKENHERE"
#          replace: "${{ secrets.GITHUB_TOKEN }}"
#          include: "nuget.config"

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Add GitHub package source
        run: dotnet nuget add source --username bcolemutech --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bcolemutech/index.json"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
