name: PR Verify

on:
  pull_request:
    branches: [ master ]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "TOKENHERE"
          replace: "${{ secrets.PACKAGE_TOKEN }}"
          include: "NuGet.Config"

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore --configfile "./DolApi/NuGet.Config"

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
